language: c
compiler:
  - clang
  - gcc

env:
  matrix:
#    - BUILD=hstox
    - BUILD=toxcore

addons:
  apt:
    sources:
      - avsm
    packages:
      - check
      - libvpx-dev
      - opam            # For apidsl and Frama-C.
      - texinfo         # For libconfig.

cache:
  directories:
    - $HOME/cache

install:
  # Globally used environment variables.
  - export CACHE_DIR=$HOME/cache
  - export OPAMROOT=$CACHE_DIR/.opam
  - export PKG_CONFIG_PATH=$CACHE_DIR/lib/pkgconfig
  - export ASTYLE=$CACHE_DIR/astyle/build/gcc/bin/astyle
  # Install required packages.
  - other/travis/${BUILD}-install

script:
  - other/travis/${BUILD}-script

after_script:
  - other/travis/${BUILD}-after_script

#notifications:
#  email: false
#
#  irc:
#    channels:
#      - "chat.freenode.net#tox-dev"
#    on_success: always
#    on_failure: always
