---
# For Pull Requests, we build only the first three jobs: autotools on Linux,
# cmake on Linux, and cmake on Windows 32 bit.
#
# For branch builds and cron builds (once a day), we build all the jobs. This
# is achieved using the "if: type IN (push, api, cron)" fields in the matrix.

language: c

matrix:
  include:
    - stage: "Stage 1"
      env: JOB=tox-bootstrapd-docker
      services: [docker]
      script:        .travis/$JOB
  fast_finish: true

cache:
  directories:
    - $HOME/.cache/bazel
    - $HOME/cache
    - /opt/freebsd/cache

notifications:
  irc:
    channels:
      - "chat.freenode.net#toktok-status"
    template:
      - "%{result} %{repository_name} %{build_url}"
      - "#%{build_number} changes: %{compare_url}"
