language: c

matrix:
  include:
    - env: BUILD=hstox
      language: haskell
      ghc: 7.8
    - env: BUILD=toxcore
      compiler: clang
    - env: BUILD=toxcore
      compiler: gcc

addons:
  apt:
    sources:
      - avsm
    packages:
      - check
      - libvpx-dev
      - opam            # For apidsl and Frama-C.
      - texinfo         # For libconfig.

cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc
    - $HOME/cache

install:
  # Globally used environment variables.
  - export CACHE_DIR=$HOME/cache
  - export OPAMROOT=$CACHE_DIR/.opam
  - export LD_LIBRARY_PATH=$CACHE_DIR/lib
  - export PKG_CONFIG_PATH=$CACHE_DIR/lib/pkgconfig
  - export ASTYLE=$CACHE_DIR/astyle/build/gcc/bin/astyle
  # Install required packages.
  - other/travis/${BUILD}-install

script:
  - other/travis/${BUILD}-script

after_script:
  - other/travis/${BUILD}-after_script
