---
# For Pull Requests, we build only the first three jobs: autotools on Linux,
# cmake on Linux, and cmake on Windows 32 bit.
#
# For branch builds and cron builds (once a day), we build all the jobs. This is
# achieved using the "if: type IN (push, api, cron)" fields in the jobs list.

language: c
os: linux

jobs:
  include:
    - stage: "Stage 1"
      env: JOB=cmake-linux
      compiler: gcc
      addons:
        apt:
          packages:
            - libconfig-dev          # For tox-bootstrapd.
            - libopus-dev            # For toxav.
            - libgtest-dev           # For unit tests.
            - libvpx-dev             # For toxav.
            - ninja-build
            - pylint
      install:       .travis/$JOB install
      script:        .travis/$JOB script
      after_script:  .travis/upload-coverage
    - stage: "Stage 1"
      env: JOB=autotools-linux
      compiler: clang
      addons:
        apt:
          packages:
            - libconfig-dev         # For tox-bootstrapd.
            - libopus-dev           # For toxav.
            - libvpx-dev            # For toxav.
      install:       .travis/$JOB install
      script:        .travis/$JOB script
    - stage: "Stage 1"
      env: JOB=bazel-linux
      compiler: clang
      before_install:
        # Clear bazel installation.
        - rm -rf $HOME/.cache/bazel/_bazel_$USER/install
        # Get toktok-stack, which contains the bazel workspace.
        - cd ..
        - git clone --depth=1 --branch=upgrade-bazel https://github.com/iphydf/toktok-stack
        - rm -rf toktok-stack/c-toxcore
        - mv c-toxcore toktok-stack/
        - cd toktok-stack/c-toxcore
      install:       .travis/$JOB install
      script:        .travis/$JOB script
      before_cache:
        # Clear bazel installation.
        - rm -rf $HOME/.cache/bazel/_bazel_$USER/install
    - stage: "Stage 1"
      if: type IN (push, api, cron)
      env: JOB=cmake-win32
      services: [docker]
      install:       .travis/$JOB install
      script:        .travis/$JOB script
    - stage: "Stage 1"
      if: type IN (push, api, cron)
      env: JOB=cmake-win64
      services: [docker]
      install:       .travis/$JOB install
      script:        .travis/$JOB script
    - stage: "Stage 1"
      if: type IN (push, api, cron)
      env: JOB=cmake-freebsd
      install:       .travis/$JOB-stage1 install
      script:        .travis/$JOB-stage1 script
    - stage: "Stage 1"
      if: type IN (push, api, cron)
      env: JOB=cmake-osx
      os: osx
      install:       .travis/$JOB install
      script:        .travis/$JOB script
    - stage: "Stage 1"
      if: type IN (push, api, cron)
      env: JOB=tox-bootstrapd-docker
      services: [docker]
      script:        .travis/$JOB
    - stage: "Stage 2"
      if: type IN (push, api, cron)
      env: JOB=cmake-freebsd
      install:       .travis/$JOB-stage2 install
      script:        .travis/$JOB-stage2 script
  fast_finish: true

cache:
  directories:
    - $HOME/.cache/bazel
    - $HOME/cache
    - /opt/freebsd/cache

notifications:
  irc:
    channels:
      - "chat.freenode.net#toktok-status"
    template:
      - "%{result} %{repository_name} %{build_url}"
      - "#%{build_number} changes: %{compare_url}"
