language: c

matrix:
  include:
    - env: JOB=hstox ENV=linux
      language: haskell
      ghc: 7.8
    - env: JOB=autotools ENV=linux
      compiler: gcc
    - env: JOB=toxcore ENV=linux
      compiler: clang

addons:
  apt:
    sources:
      - avsm
    packages:
      - check
      - libcv-dev             # For av_test.
      - libhighgui-dev        # For av_test.
      - libopencv-contrib-dev # For av_test.
      - libsndfile1-dev       # For av_test.
      - libvpx-dev
      - opam                  # For apidsl and Frama-C.
      - portaudio19-dev       # For av_test.
      - texinfo               # For libconfig.

cache:
  directories:
    # Although Travis documentation says not to rely on the value of $HOME, we
    # rely on it here because cabal installs its packages there by default. If
    # that ever changes, these values need to be updated.
    # Note that we can't use shell expressions in these paths, so we can't ask
    # cabal where its data is stored.
    - $HOME/.cabal
    - $HOME/.ghc
    - $HOME/cache

install:      other/travis/phase $JOB $ENV install
script:       other/travis/phase $JOB $ENV script
after_script: other/travis/phase $JOB $ENV after_script

notifications:
  irc: "chat.freenode.net#toktok-status"

branches:
  only:
    - master
