install:
# TODO(iphydf): Remove this when appveyor gets curl back, which it should have
# according to https://www.appveyor.com/docs/how-to/download-file/.
- choco install curl
- refreshenv
# libcheck
- curl -L https://github.com/libcheck/check/releases/download/0.11.0/check-0.11.0.tar.gz -o check.tar.gz
- tar zxf check.tar.gz
- cd check-0.11.0
- cmake .
- msbuild INSTALL.vcxproj
- dir
- cd ..
# libsodium
- mkdir libsodium && cd libsodium
- curl -L https://download.libsodium.org/libsodium/releases/libsodium-1.0.11-msvc.zip -o libsodium.zip
- unzip libsodium.zip
- cd ..
# pthreads-win32
- mkdir pthreads-win32 && cd pthreads-win32
- curl -L ftp://sourceware.org/pub/pthreads-win32/pthreads-w32-2-9-1-release.zip -o pthreads.zip
- unzip pthreads.zip
- cd ..

before_build:
- cmake . -DBOOTSTRAP_DAEMON=OFF -DENABLE_SHARED=OFF -DBUILD_TOXAV=OFF
- dir
- ctest -N

build:
  project: INSTALL.vcxproj

branches:
  only:
  - master
