#!/bin/sh

# Build toxcore and run tests.
RUN $CMAKE -B$BUILD_DIR -H. -DCMAKE_INSTALL_PREFIX:PATH=$CURDIR/_install -DDEBUG=ON -DASSOC_DHT=ON

RUN make -C $BUILD_DIR -j$NPROC -k install
if $TESTS; then
  ulimit -c unlimited
  export CK_FORK=no
  export CTEST_OUTPUT_ON_FAILURE=1
  RUN make -C $BUILD_DIR -j$NPROC test
fi
