#!/bin/sh

# Update ruby
rvm get stable
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
rvm use ruby --install --default
echo rvm_auto_reload_flag=1 >> ~/.rvmrc

brew install libsodium libvpx opus libconfig check astyle

