#!/bin/sh

set -e

SOURCE_DIR="$1"
APIDSL="$2"
ASTYLE="$3"

# Go to the source root.
if [ -z "$SOURCE_DIR" ]; then
  SOURCE_DIR=.
fi
cd "$SOURCE_DIR"

if [ -z "$ASTYLE" ] || ! which "$ASTYLE"; then
  ASTYLE=astyle
fi

if ! which "$ASTYLE"; then
  # If we couldn't find or install an astyle binary, don't do anything.
  echo "Could not find an astyle binary; please install astyle."
  exit 1
fi

if ! which "$APIDSL"; then
  if [ -f ../apidsl/apigen.native ]; then
    APIDSL=../apidsl/apigen.native
  else
    APIDSL=apidsl_curl
  fi
fi

apidsl_curl() {
  curl -X POST --data-binary @"$1" https://apidsl.herokuapp.com/apidsl
}

INTERFACES=""
INTERFACES="$INTERFACES toxcore/crypto_core"
INTERFACES="$INTERFACES toxcore/tox"
INTERFACES="$INTERFACES toxav/toxav"

# Check if the generated .h files match apidsl .api.h files.
for I in $INTERFACES; do
  $APIDSL $I.api.h > $I.h
done

SOURCES=`find . -name "*.[ch]" -and -not -name "*.api.h" -and -not -wholename "*crypto_pwhash*" -and -not -wholename "./super_donators/*"`

$ASTYLE -n --options=other/astyle/astylerc $SOURCES

git diff --exit-code
